language: python

sudo: required

services:
  - docker
  - elasticsearch

branches:
  only:
    - master

env:

before_install:
  - docker version
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.11.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.11.deb && sudo service elasticsearch restart

before_script:
  - sleep 10

install:
  - export PATH=$(pwd)/bin:$PATH

script:
  - make test

after_script:
