language: python
python:
  - "3.6"

sudo: required

services:
  - docker
  - elasticsearch

branches:
  only:
    - master

env:

before_install:
  - docker version
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.11.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.11.deb && sudo service elasticsearch restart
  - sleep 10
  - curl http://localhost:9200

install:
  - export PATH=$(pwd)/bin:$PATH
  - pip install -r requirements.txt

script:
  - export KB_DEPLOYMENT_CONFIG=test.cfg
  - make test

after_script:
